name: Build and Deploy
on: 
  push:
    branches:
      - feature/continous-publish
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@feature/continous-publish

    - name: Install Dependencies
      run: npm install

    - name: Webpack build
      run: npm run build

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
